### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'jsObjectReference')

### ISSUE THREAD

**Issue by gsmerkoljMXP** [JByfordRew/BlazorTransitionableRoute#12]
I get this error in JsInterop class: 

System.ArgumentNullException: Value cannot be null. (Parameter 'jsObjectReference')
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at BlazorTransitionableRoute.JsInterop.<Init>d__2`1[[BlazorTransitionableRoute.TransitionableRoutePrimary, BlazorTransitionableRoute, Version=4.1.13.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at BlazorTransitionableRoute.TransitionableRoutePrimary.HandleFirstRender()
   at BlazorTransitionableRoute.TransitionableRoutePrimary.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState) 
 System.ArgumentNullException: Value cannot be null. (Parameter 'jsObjectReference')
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at BlazorTransitionableRoute.JsInterop.<Init>d__2`1[[BlazorTransitionableRoute.TransitionableRoutePrimary, BlazorTransitionableRoute, Version=4.1.13.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at BlazorTransitionableRoute.TransitionableRoutePrimary.HandleFirstRender()
   at BlazorTransitionableRoute.TransitionableRoutePrimary.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState

I'm assuming js file is not loaded before InvokeVoidAsync is called. Also when I debug this class module.Value is null. Wraping this into if condition (module.Value is not null) won't do because then navigation doesn't work at all and it's always the same page as on first render. 
For now I have solved this with Task.Delay(100) before module.Value is called. But this is only temorary solution as it is bad code practice.

**Comment by gsmerkoljMXP** [comment]
Found out that version 3.1 works withouth this issue

**Comment by JByfordRew** [comment]
Many thanks indeed for doing this. Appreciated.
